# Generated by Django 4.1.2 on 2023-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning10', models.IntegerField(default='')),
                ('afternoon2', models.IntegerField(default='')),
                ('evening6', models.IntegerField(default='')),
                ('night10', models.IntegerField(default='')),
                ('firsttotal', models.IntegerField(default='')),
                ('firstrupess10', models.IntegerField(default='')),
                ('rupess2', models.IntegerField(default='')),
                ('rupess6', models.IntegerField(default='')),
                ('lastrupess10', models.IntegerField(default='')),
                ('lasttotal', models.IntegerField(default='')),
            ],
        ),
    ]
